Dockerize
BDE-ESIEE/bde-esiee pull request #37
Opened 2020-07-23 14:25 UTC by six3six

2020-07-23 14:52 UTC, wallforfry requested changes

2020-07-23 14:52 UTC, wallforfry commented on docker/docker-compose.yml
> +volumes:
Ajoute un volume pour les uploads du container "web"

2020-07-23 14:52 UTC, wallforfry commented on Dockerfile
> +RUN mv docker/init.sh .
Pourquoi pas mettre directement init.sh au bon endroit ?

2020-07-23 14:52 UTC, wallforfry commented on Dockerfile
> +ENTRYPOINT ["bash", "-c"]
C'est bizarre comme entrypoint

2020-07-26 14:40 UTC, six3six commented on Dockerfile
> +RUN mv docker/init.sh .
Je pouvais mais ca me paraissais plus lisible pour le dev.
Après c'est vous qui voyez

2025-09-09 07:45 UTC, closed without merging